language: python
python:
  - "2.7"
env:
  - DJANGO=1.4
install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements.txt
  - pip install flake8
script:
  - flake8 kanisa
  - ./kanisa/example_project/manage.py test kanisa
