language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install flake8 --use-mirrors
script:
  - flake8 kanisa
  - ./kanisa/example_project/manage.py test kanisa
